config/routes.rb
Mytwocents::Application.routes.draw do
  root'posts#index'
  resources :posts, only: [:create, :index, :destroy, :show] do
    collection do
      get 'nav_counter' => 'posts#nav_counter'
      get 'post_feed' => 'posts#post_feed'
      post 'post_feed' => 'posts#post_feed_filter'
      get 'nav_new_posts' => 'posts#nav_new_posts'
    end
  end
  resources :comments, only: [:create]

  get "pages/landing"
  get "pages/panel"
  get "pages/terms"

  devise_for :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true, length: { maximum: 4000 }
  validates :mood_id, presence: true
  validates :post_id, presence: true

  belongs_to :user
  belongs_to :post, touch: true

  def self.posted
    where(deleted: false)
  end

  def self.deleted_posts
    where(deleted: true)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :content, presence: true, length: { maximum: 4000 }
  validates :mood_id, presence: true
  belongs_to :user
  has_many :comments

  def self.posted
    where(deleted: false)
  end

  def self.deleted_posts
    where(deleted: true)
  end

  def get_cents
    2 + (comments.posted.count * 2)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.new(comment_params)
    if user_signed_in?
      comment.user = current_user
    end


    respond_to do |format|
      if comment.save

        format.html { 
          redirect_to post_path(comment_params[:post_id])
        }
        format.js {
        @comments = Comment.where(post_id: comment_params[:post_id])
        @update_post = Post.find(comment_params[:post_id]).get_cents
        }
      else

        if comment.errors.messages[:content]
          @error = "Comment can not be blank."
        elsif comment.errors.messages[:mood_id]
          @error = "Please chose a mood."
        end

        format.html {
          flash[:alert] = @error
          redirect_to post_path(comment_params[:post_id])
        }
        format.js {
          render 'posts/form_alert'
        }
      end
      session[:last_post] = Post.posted.count
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content,:mood_id, :post_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
  end

  def panel
    if current_user.admin == true
      @post_count = Post.all.count
      @posted_count = Post.posted.count
      @deleted_posts = Post.deleted_posts
    else
      redirect_to root_path
    end
  end

  def terms
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
    post = Post.new(post_params)
    if user_signed_in?
      post.user = current_user
    end

    respond_to do |format|
      if post.save
        format.html { redirect_to root_path }
        format.js { }
      else

        if post.errors.messages[:content]
          @error = "Post can not be blank."
        elsif post.errors.messages[:mood_id]
          @error = "Please chose a mood."
        end

        format.html {
          flash[:alert] = @error
          session[:modal] = true
          redirect_to root_path
        }
        format.js {
          render 'form_alert'
        }
      end
      save_number_of_posts
    end
  end

  def destroy
    if current_user.admin = true
      post = Post.find(params[:id])
      post.deleted = true
      post.save
    end
    redirect_to root_path
  end

  def index
    @post = Post.new

    if session[:filter] == 'new' || session[:filter].nil?
      @posts = return_newest_posts
    elsif session[:filter] == 'comment'
      @posts = return_latest_commented
    end


    @number = Post.posted.count

    navbar_counter
    save_number_of_posts

    @post_modal = false
    if session.delete(:modal) == true
      @post_modal = true
    end

  end

  def nav_counter
    navbar_counter
    render partial: 'shared/navbar/happy_meter'
  end

  def nav_new_posts
    n_new_posts = Post.posted.count - session[:last_post]
    render partial: 'shared/navbar/new_posts', locals: { new: n_new_posts }
  end

  def post_feed
    save_number_of_posts
    render return_newest_posts
  end

  def post_feed_filter
    if params[:filter] == 'new'
      @posts = return_newest_posts
      session[:filter] = 'new'
    elsif params[:filter] == 'comment'
      @posts = return_latest_commented
      session[:filter] = 'comment'
    end
    render @posts
  end

  def show
    @post = Post.posted.find(params[:id])

    @comments = Comment.all.where(post_id: params[:id])
    @comment = Comment.new

    @show = true
    @number = Post.posted.count

    save_number_of_posts
    navbar_counter

  end

  private

  def return_newest_posts
      Post.posted.limit(100).order("created_at DESC")
  end

  def return_latest_commented
      commented_posts = Post.posted.joins(:comments).distinct.limit(100).order("updated_at DESC")
      if commented_posts.count < 100
        commented_posts + Post.posted.joins('left outer join comments on posts.id=comments.post_id').select('posts.*,comments.post_id').where('comments.post_id is null').limit(100 - commented_posts.count).order("created_at DESC")
      end
  end

  def post_params
    params.require(:post).permit(:content,:mood_id)
  end

  def save_number_of_posts
    session[:last_post] = Post.posted.count
  end

  def navbar_counter
    @happy_meter = Post.posted.average(:mood_id)

    posts = Post.posted.count * 2
    comments = Comment.posted.count * 2
    @total_cents = (posts + comments) * 0.01
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


  def get_mood(mood_id)
    case mood_id

    when 100
      return "fa fa-smile-o"

    when 50
      return "fa fa-meh-o"

    when 1
      return "fa fa-frown-o"

    end 
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
    <div class="media">

        <!-- Mood -->
        <span class="pull-left">
            <i class="<%= get_mood(comment.mood_id) %> icon mood" %></i>
        </span>


        <!-- Time -->
        <small class="text-left text-muted pull-left">
            <%= time_ago_in_words(comment.created_at) %> ago
        </small>

        <!-- Admin sticker -->
        <% if ! comment.user.nil? && comment.user.admin == true %>
            <span class="pull-left stamp">mytwocents.io</span>
        <% end %>

        <!-- Comments -->
        <span class="pull-right">
            <small class="purple">+ 2&cent;</small>
        </span>
        <div class="clearfix"></div>


        <!-- Comment -->
        <div class="media-body">
            <%= auto_link(simple_format(h  comment.content), html: {rel: "nofollow"} ) %>
        </div>

    </div>

app/views/comments/create.js.erb
$('#form_content').val('');
$('#form_mood_id').val('');
$('.mood-row i').removeClass('highlight');

$('.comments').html("<%= escape_javascript(render(@comments)) %>");
$('.cents').text("<%= @update_post %> cents");

$('.new_posts').load('/posts/nav_new_posts');
$('.happy-row').load('/posts/nav_counter');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>mytwocents.io</title>
    <%# Mobile responsivenes %>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <%= stylesheet_link_tag 'application', '//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">

          <%# Logo normal + mobile %>
          <%= link_to image_tag("logo_white.png", class: "pull-left hidden-xs hidden-sm"), root_path %>
          <%= link_to image_tag("logo_79x45.png", class: "pull-left visible-xs visible-sm logo-sm"), root_path %>

          <%# Only show when in index? %>
          <% if controller_name == 'posts' %>

            <%# New post button %>
            <span class="pull-right visible-xs visible-sm">
              <%= render 'shared/navbar/right_button' %>
            </span>

            <%# Happy meter %>
            <span class="happy-row navbar-text pull-right visible-xs visible-sm">
              <%= render 'shared/navbar/happy_meter' %>
            </span>

          <% end %>

          <%# Logged in user dropdown %>
          <% if user_signed_in?%>
                <%= render 'shared/navbar/user_dropdown' %>
          <% end %>
      </div><!--/.navbar-header -->

      <div class="navbar-collapse collapse hidden-xs hidden-sm">

        <ul class="nav navbar-nav navbar-right ">
            <%# Start if %>
            <% if controller_name == 'posts' %>

              <%# Happy meter %>
              <li class="happy-row">
                <%= render 'shared/navbar/happy_meter' %>
              </li>

              <%# Displays new posts %>
              <li class="new_posts">
                <%= render 'shared/navbar/new_posts', new: 0 %>
              </li>

              <%# New post button %>
              <li>
                <%= render 'shared/navbar/right_button' %>
              </li>
            <% end %>
        </ul>

      </div><!--/.nav-collapse -->
    </div>
  </div><!--/.container -->

  <%= render 'shared/g_analytics' %>
  <%= yield %>
  <%= render 'shared/user_voice' %>

  </body>
</html>

app/views/pages/landing.html.erb
<h1>Pages#landing</h1>
<p>Find me in app/views/pages/landing.html.erb</p>

app/views/pages/panel.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12 panel">
            <h3>Admin Panel</h3>
            <p>Total Post count: <%= @post_count %></p>
            <p>Post count: <%= @posted_count %></p>
            <p>Deleted Post count: <%= @deleted_posts.count %></p>
            <h3>Deleted posts</h3>
            <%= render @deleted_posts %>
        </div>
    </div>
</div>

app/views/pages/terms.html.erb
<div id="portfolio" class="portfolio_page">
	<div class="container">
		<!-- header -->
		<h2 class="section_header">
		  <hr class="left visible-desktop">
		  <span style="font-weight:300">Terms & Conditions</span>
		  <hr class="right visible-desktop">
		</h2>
		<div class="row">
			<div class="span8 offset2">
				<span style="font-weight:300;font-size:0.8em">last updated: 2014-03-08</span>
				<br>		
				<br>
		
		<h4>[1] Introduction</h4>
		<p>
			These terms of use govern your use of our website; by using our website, you agree to these terms of use in full. If you disagree with these terms of use or any part of these terms of use, you must not use our website.
		</p>
		<p>
			You must be at least 15 years of age to use our website. By using our website and by agreeing to these terms of use, you warrant and represent that you are at least 15 years of age.
		</p>
		<p>
			Our website uses cookies. By using our website and agreeing to these terms of use, you consent to our use of cookies.
		</p>
		<br>
 
		<h4>[2] Credit</h4>
		<p>
			This document was created using an SEQ Legal template.
		</p>
		<br>
 
		<h4>[3] Licence to use website</h4>
		<p>
			Unless otherwise stated, we or our licensors own the intellectual property rights in the website and material on the website. Subject to the licence below, all these intellectual property rights are reserved.
		</p>
		<p>
			You may view, download for caching purposes only, and print pages from the website for your own personal use, subject to the restrictions set out below and elsewhere in these terms of use.
		</p>
			You must not:
		<ul style="padding-left:20px">
			<li style="list-style-type:square">republish material from this website (including republication on another website);</li>
			<li style="list-style-type:square">sell, rent or sub-license material from the website;</li>
			<li style="list-style-type:square">show any material from the website in public;</li>
			<li style="list-style-type:square">reproduce, duplicate, copy or otherwise exploit material on our website for a commercial purpose</li>
		</ul>
		<br>
		
		<h4>[4] Acceptable use</h4>
		<p>
			You must not use our website in any way that causes, or may cause, damage to the website or impairment of the availability "or accessibility of the website; or in any way which is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity.
		</p>
		<p>
			You must not use our website to copy, store, host, transmit, send, use, publish or distribute any material which consists of (or is linked to) any spyware, computer virus, Trojan horse, worm, keystroke logger, rootkit or other malicious computer software.
		</p>
 	 	<p>
			You must not conduct any systematic or automated data collection activities (including, without limitation, scraping, data mining, data extraction and data harvesting) on or in relation to our website without our express written consent.
		</p> 
		<br>
 
		<h4>[5] Restricted access</h4>
		<p>
			Access to certain areas of our website is restricted. We reserve the right to restrict access to other areas of our website, or indeed our whole website, at our discretion.
		</p>
		<p>
			If you generate a user ID and password to enable you to access restricted areas of our website or other content or services, you must ensure that the password is kept confidential.
		</p>
		<p>
			You must notify us in writing immediately if you become aware of any unauthorized use of your account or password.
		</p>
		<p>
			You are responsible for any activity on our website arising out of any failure to keep your password confidential and may be held liable for any losses arising out of such a failure.
		</p>
		<p>
			You must not use any other person's user ID and password to access our website.
		</p>
		<p>
			We may disable your user ID and password at any time in our sole discretion with or without notice or explanation.
		</p>
		<br>
 
		<h4>[6] User content</h4>
 	 	<p>
			In these terms of use, "your content" means material (including, without limitation, text, images, audio material, video material and audio-visual material) that you submit to our website, for whatever purpose.
		</p>
		<p>
			You grant to us a worldwide, irrevocable, non-exclusive, royalty-free licence to use, reproduce, adapt, publish, translate and distribute your content in any existing or future media. You also grant to us the right to sub-license these rights and the right to bring an action for infringement of these rights.
		</p>
		<p>
			You warrant and represent that your content will comply with these terms of use.
		</p>
		<p>
			Your content must not be illegal or unlawful, must not infringe any third party's legal rights and must not be capable of giving rise to legal action whether against you or us or a third party (in each case under any applicable law).
		</p>
		<p>
			You must not submit any content to the website that is or has ever been the subject of any threatened or actual legal proceedings or other similar complaint.
		</p>
		<p>
			We reserve the right to edit or remove any material submitted to our website, or stored on our servers, or hosted or published upon our website.
		</p>
		<p>
			Notwithstanding our rights under these terms of use in relation to your content, we do not undertake to monitor the submission of such content to, or the publication of such content on, our website.
		</p>
		<br>
 
		<h4>[7] Limited warranties</h4>
 	 	<p>
			We do not warrant the completeness or accuracy of the information published on this website; nor do we commit to ensuring that the website remains available or that the material on the website is kept up to date.
		</p>
		<p>
			To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to this website and the use of this website (including, without limitation, any warranties implied by law in respect of satisfactory quality, fitness for purpose and/or the use of reasonable care and skill).
		</p>
		<br>
 
		<h4>[8] Limitations and exclusions of liability</h4>
		<p>
			Nothing in these terms of use will: (a) limit or exclude our or your liability for death or personal injury resulting from negligence; (b) limit or exclude our or your liability for fraud or fraudulent misrepresentation; (c) limit any of our or your liabilities in any way that is not permitted under applicable law; or (d) exclude any of our or your liabilities that may not be excluded under applicable law.
		</p>
		<p>
			The limitations and exclusions of liability set out in this Section and elsewhere in these terms of use: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under these terms of use or in relation to the subject matter of these terms of use, including liabilities arising in contract, in tort (including negligence) and for breach of statutory duty.
		</p>
		<p>
			To the extent that the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.
		</p>
		<p>
			We will not be liable to you in respect of any losses arising out of any event or events beyond our reasonable control.
		</p>
		<p>
			We will not be liable to you in respect of any business losses, including (without limitation) loss of or damage to profits, income, revenue, use, production, anticipated savings, business, contracts, commercial opportunities or goodwill.
		</p>
		<p>
			We will not be liable to you in respect of any loss or corruption of any data, database or software.
		</p>
		<p>
			We will not be liable to you in respect of any special, indirect or consequential loss or damage.
		</p>
		<br>
 
		<h4>[9] Indemnity</h4>
		<p>
			You hereby indemnify us and undertake to keep us indemnified against any losses, damages, costs, liabilities and expenses (including, without limitation, legal expenses and any amounts paid by us to a third party in settlement of a claim or dispute on the advice of our legal advisers) incurred or suffered by us arising out of any breach by you of any provision of these terms of use, or arising out of any claim that you have breached any provision of these terms of use.
		</p>
		<br>
 
		<h4>[10] Breaches of these terms of use</h4>
		<p>
			Without prejudice to our other rights under these terms of use, if you breach these terms of use in any way, we may take such action as we deem appropriate to deal with the breach, including suspending your access to the website, prohibiting you from accessing the website, blocking computers using your IP address from accessing the website, contacting your internet service provider to request that they block your access to the website and/or bringing court proceedings against you.
		</p>
		<br>
 
		<h4>[11] Variation</h4>
		<p>
			We may revise these terms of use from time to time. Revised terms of use will apply to the use of our website from the date of publication of the revised terms of use on our website.
		</p>
		<br>
 
		<h4>[12] Assignment</h4>
		<p>
			We may transfer, sub-contract or otherwise deal with our rights and/or obligations under these terms of use without notifying you or obtaining your consent.
		</p>
		<p>
			You may not transfer, sub-contract or otherwise deal with your rights and/or obligations under these terms of use.
		</p>
		<br>
 
		<h4>[13] Severability</h4>
		<p>
			If a provision of these terms of use is determined by any court or other competent authority to be unlawful and/or unenforceable, the other provisions will continue in effect. If any unlawful and/or unenforceable provision would be lawful or enforceable if part of it were deleted, that part will be deemed to be deleted, and the rest of the provision will continue in effect.
		</p>
		<br>
 
		<h4>[14] Exclusion of third party rights</h4>
		<p>
			These terms of use are for the benefit of you and us, and are not intended to benefit any third party or be enforceable by any third party. The exercise of our and your rights in relation to these terms of use is not subject to the consent of any third party.
		</p>
		<br>
 
		<h4>[15] Entire agreement</h4>
		<p>
			Subject to the first paragraph of Section [8], these terms of use, together with our privacy policy, constitute the entire agreement between you and us in relation to your use of our website and supersede all previous agreements in respect of your use of our website.
		</p>
		<br>
 
		<h4>[16] Law and jurisdiction</h4>
		<p>
			These terms of use will be governed by and construed in accordance with Korean law, and any disputes relating to these terms of use will be subject to the non-exclusive jurisdiction of the courts of the Republic of South Korea.
		</p>
		<br>
 
	</div>
</div>
				
	</div> <!-- end of container -->
</div> <!-- end of portfolio -->

app/views/posts/_form.html.erb
<%= form_for(post, remote: true) do |f| %>

    <% if @show.nil? %>
        <%= f.text_area(:content, placeholder:'Write up to 4,000 characters (you can also copy & paste links)!', size:'66x6', maxlength:'4000', class: "form-control", id: "form_content") %>
    <% else %>
        <%= f.text_area(:content, placeholder:'Add a comment (you can also copy & paste links)!', size:'66x6', maxlength:'4000', class: "form-control", id: "form_content") %>
    <% end %>

    <div class="text-right">
        <div class='myAlert text-center alert alert-danger hidden'>
            <%= @error %>
        </div>

        <% if flash[:alert] %>
            <div class="alert alert-warning alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <%= flash[:alert] %>
            </div>
        <% end %>

        <%= f.submit "Submit", class: "btn btn-default btn-lg pull-right", data: {disable_with: "Loading"} %>
        <%= f.hidden_field :post_id, value: params[:id], id: "form_post_id" %>
        <%= f.hidden_field :mood_id, value: '', id: "form_mood_id" %>
    </div>

    <div class="text-right"><small class="text-muted mood-row">Choose a mood</small></div>

    <div class="mood-row pull-right">
        <i class="fa fa-smile-o mood-lg" data-value="100"></i>
        <i class="fa fa-meh-o mood-lg" data-value="50"></i>
        <i class="fa fa-frown-o mood-lg" data-value="1"></i>
    </div>


    <div class="clearfix"></div>
<% end %>

app/views/posts/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close close-modal" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title text-center text-muted" id="myModalLabel">Give your two cents</h4>
      </div>
      <div class="modal-body">
            <%= render partial: 'posts/form' %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_new_post_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close close-modal" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title text-center text-muted" id="myModalLabel">Give your two cents</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'posts/form', locals: {post: @post} %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="well">
    <div class="media">

        <!-- Mood -->
        <span class="pull-left">
            <i class="<%= get_mood(post.mood_id) %> icon mood" %></i>
        </span>

        <!-- Time -->
        <small class="text-left text-muted pull-left">
            <%= time_ago_in_words(post.created_at) %> ago
        </small>

        <!-- Admin sticker -->
        <% if ! post.user.nil? && post.user.admin == true %>
            <span class="pull-left stamp">mytwocents.io</span>
        <% end %>

        <!-- Comments -->
        <span class="pull-right">
                <small class="cents purple"><%= post.get_cents %>&cent;</small>
            <% if @show.nil? %>
                <% if post.comments.count > 0 %>
                    <%= link_to '<i class="fa fa-comments icon"></i>'.html_safe, post_path(post.id) %>
                <% else %>
                    <%= link_to '<i class="fa fa-comment-o icon"></i>'.html_safe, post_path(post.id) %>
                <% end %>
            <% else %>
                <% if post.comments.count > 0 %>
                    <i class="fa fa-comments icon mood"></i>
                <% else %>
                    <i class="fa fa-comment-o icon mood"></i>
                <% end %>
            <% end %>
        </span>
        <div class="clearfix"></div>

        <!-- Post -->
        <div class="media-body">
            <% if post.content.length > 500 && @show.nil? %>
                <%= auto_link(simple_format(h truncate post.content, length: 500), html: {rel: "nofollow"} ) %>
                <%= link_to "<small>Read more</small>".html_safe, post  %>
            <% else %>
                <%= auto_link(simple_format(h post.content), html: {rel: "nofollow"} ) %>
            <% end %>
        </div>

        <% if user_signed_in? && current_user.admin == true %>
            <%= link_to "Delete ##{post.id}", post, method: :delete, data: { confirm: "Del?" } %>
        <% end %>
    </div>
</div>

app/views/posts/_post_header.html.erb
<h4 class="caps text-center">
    Engage with others by giving your two cents.
    <br>
    <br>
    <a href="https://www.facebook.com/pages/mytwocentsio/251021331737236" target="_blank">
        <i class="fa fa-facebook"></i>
    </a>
    <a href="https://twitter.com/mytwocentsio" target="_blank">
        <i class="fa fa-twitter"></i>
    </a>
    <a href="https://plus.google.com/105622011272327226077" rel="publisher" target="_blank">
        <i class="fa fa-google-plus"></i>
    </a>
</h4>

app/views/posts/_welcome_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="welcomeModal" tabindex="-1" role="dialog" aria-labelledby="welcomeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title text-center text-muted" id="welcomeModalLabel">Give your two cents</h4>
      </div>
      <div class="modal-body text-center">
        <p>Engage with others by giving your two cents.</p>
        <p>Check out how your two cents increase in value.</p>

        <br>
        <button type="button" class="center-block btn btn-default" data-dismiss="modal" aria-hidden="true">OK</button>
      </div>
    </div>
  </div>
</div>

app/views/posts/alert.js.erb
$('.myAlert').removeClass('hidden').hide();
$('.myAlert').text('<%= @error %>');
$('.myAlert').slideDown("fast");

app/views/posts/create.js.erb
$('.posts').load('/posts/post_feed');
$('.new_posts').load('/posts/nav_new_posts');
$('.happy-row').load('/posts/nav_counter');
$('#myModal').modal('hide');
$('.navbar-collapse').collapse('hide');

app/views/posts/index.html.erb
<%= render 'new_post_modal' %>

<% if @post_modal == true %>
    <% @post_modal = false %>
    <%= javascript_tag "$('#myModal').modal('show')" %>
<% end %>

<% if cookies[:welcome].nil? %>
    <%  cookies.permanent[:welcome] = true%>
    <%= render 'welcome_modal' %>
    <%= javascript_tag "$('#welcomeModal').modal('show')" %>
<% end %>

<% if session[:filter] == 'new' || session[:filter].nil? %>
    <% new = "btn-filter-a" %>
    <% comment = "" %>
<% elsif session[:filter] == 'comment'%>
    <% new = "" %>
    <% comment = "btn-filter-a" %>
<% end %>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <%= render 'post_header' %>
            <div class="row">
                <div class="media col-md-6 col-md-offset-3">
                    <div class="btn btn-filter col-xs-6 col-md-6 <%= new %>" data-value="new">Latest posts</div>
                    <div class="btn btn-filter col-xs-6 col-md-6 <%= comment %>" data-value="comment">Last commented</div>
                </div>

                <div class="">
        <img class="well loaderImg centered" src="http://careers.utc.com/Styles/Sites/UTS/images/preloader_transparent.gif"/>
                </div>

                <div class="col-md-6 col-md-offset-3 posts">
                    <%= render @posts %>
                </div>
            </div>
        </div>
    </div>
</div>
<footer>
    <div>
        <p class="footer text-center">&copy; 2014 - mytwocents.io. All rights reserved</p>
        <p class="footer text-center"><%= link_to "Terms & Conditions", pages_terms_path %> - <%= link_to "Blog", 'http://mytwocentsio.wordpress.com' %></p>
    </div>
</footer>

app/views/shared/navbar/_user_dropdown.html.erb
<ul>
    <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
    <ul class="dropdown-menu">
        <% if current_user.admin? %>
            <li><%= link_to "Admin panel", pages_panel_path %></li>
    <% end %>
        <li><%= link_to "User settings", edit_user_registration_path %></li>
        <li class="divider"></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
    </ul>
    </li>
</ul>